Add support for boringssl keylog callback
zh-jq/rust-variant-ssl pull request #9
Opened 2024-05-06 19:20 UTC by mspublic

This commit adds support for the keylog callback to variant-ssl. The callback is supported by boringssl.

2024-05-07 15:28 UTC, zh-jq requested changes

2024-05-07 15:28 UTC, zh-jq commented on openssl-sys/src/handwritten/ssl.rs
> +#[cfg(any(ossl111, boringssl))]
This is not needed as the boringssl FFI is not here

2024-05-07 15:28 UTC, zh-jq commented on openssl-sys/src/handwritten/ssl.rs
> +    #[cfg(any(ossl111, boringssl))]
The same as above

2024-05-07 15:28 UTC, zh-jq commented on openssl/src/ssl/callbacks.rs
> +#[cfg(any(ossl102, boringssl))]
why change ossl111 to ossl102?

2024-05-07 15:28 UTC, zh-jq commented on openssl/src/ssl/callbacks.rs
> +#[cfg(any(ossl102, boringssl))]
same as above

2024-05-07 19:08 UTC, mspublic commented
I just noticed those typos. Sorry about that! I will fix and push upstream

2024-05-09 02:08 UTC, mspublic commented
The proper changes have been pushed upstream. Thanks for pointing out the bugs!

2024-05-09 02:08 UTC, closed without merging